manifest:
  defaults:
    remote: zephyr-upstream

  remotes:
    - name: zephyr-upstream
      url-base: https://github.com/zephyrproject-rtos

  # External projects
  #
  projects:
    - name: cmsis
      path: modules/hal/cmsis
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
    - name: hal_nordic
      path: modules/hal/nordic
      revision: d8a6ea9695ddf792bb18bb6035c13b1daac5d79c
    - name: mcuboot
      revision: a5d79cf8ccb2c71e68ef32a71d6a2716e831d12e
      path: bootloader/mcuboot
    - name: segger
      path: modules/debug/segger
      revision: 874d9e9696b00c09f9eeefe839028dc25fe44983
    - name: mbedtls
      revision: aef137b1af8aa7a0f43345c82459254b8832262e
      path: modules/crypto/mbedtls
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: v2.4.0
  self:
    path: app
